# Generated by Django 3.1.3 on 2020-11-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santapp', '0002_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='present_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='santapp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
